---
site_name: "nwb-schema-language"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://p2p_ld.github.io/nwb-schema-language
repo_url: https://github.com/p2p_ld/nwb-schema-language

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
