name: Tests

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.11]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install .[tests]
        working-directory: nwb_linkml

      - uses: pavelzw/pytest-action@v2
        working-directory: nwb_linkml
        with:
          emoji: true
          verbose: true
          job-summary: true

      - working-directory: nwb_linkml
        run: "coveralls --service=github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
